libs =

# Custom
#
import libs += libensketch-xstd%lib{ensketch-xstd}

# Logging
#
import libs += fmt%lib{fmt}

# OpenGL
#
import libs += glbinding%lib{glbinding}
import libs += glm%lib{glm}
import libs += libsfml-graphics%lib{sfml-graphics}

# Loader
#
import libs += assimp%lib{assimp}

import libs += stb_image%lib{stb_image}
import libs += stb_image_write%lib{stb_image_write}

import libs += sol2%lib{sol2}

exe{motion-lines-demo}: {hxx ixx txx cxx}{**} $libs
{
  test = true
}

cxx.poptions =+ "-I$out_root" "-I$src_root"
